# HerdNet Inference Configuration
# This config is used for running inference with trained HerdNet models

# Experiment metadata
experiment:
  name: herdnet_inference
  tags:
    - herdnet
    - inference

# Model configuration (must match training config)
model:
  num_classes: 7  # 6 animal classes + 1 background
  down_ratio: 2
  losses:
    - name: focal_loss
      idx: 0
      idy: 0
      lambda_: 1.0
      weight: null
    - name: ce_loss
      idx: 1
      idy: 1
      lambda_: 1.0
      weight: [0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]

# Dataset configuration (for loading images)
data:
  patch_size: 512
  test_csv: ${oc.env:DATA_DIR,./data}/herdnet/test_patches/gt.csv
  test_root: ${oc.env:DATA_DIR,./data}/herdnet/test_patches

  # Transform params (no augmentation for inference)
  radius: 2
  mask_down_ratio: 32

# Inference configuration
inference:
  name: HerdNetInference  # Inference registry name
  device: cuda  # Device for inference ('cuda' or 'cpu')
  checkpoint_path: ./output/best_model.pth  # Path to trained model checkpoint
  threshold: 0.5  # Detection confidence threshold (0.0-1.0)
  batch_size: 1  # Batch size for inference

# Seed for reproducibility
seed: 9292
