# HerdNet Inference Configuration
# This config is used for running inference with trained HerdNet models

# Model type (used by unified inference system)
model_type: herdnet

# Experiment metadata
experiment:
  name: herdnet_inference_test
  tags:
    - herdnet
    - inference
    - test

# Model configuration (must match training config)
model:
  num_classes: 7  # 6 animal classes + 1 background
  down_ratio: 2
  losses:
    - name: focal_loss
      idx: 0
      idy: 0
      lambda_: 1.0
      weight: null
    - name: ce_loss
      idx: 1
      idy: 1
      lambda_: 1.0
      weight: [0.1, 1.0, 2.0, 1.0, 6.0, 12.0, 1.0]

# Dataset configuration (for loading images)
data:
  patch_size: 512
  test_csv: data/herdnet/raw/groundtruth/csv/test_big_size_A_B_E_K_WH_WB.csv
  test_root: data/herdnet/raw/test

  # Transform params (no augmentation for inference)
  radius: 2
  mask_down_ratio: 32

# Evaluator configuration (for stitcher)
evaluator:
  metrics_radius: 20
  stitcher_overlap: 160
  stitcher_reduction: mean

# Inference configuration
inference:
  name: HerdNetInference  # Inference registry name
  device: cuda  # Device for inference ('cuda' or 'cpu')
  checkpoint_path: ./outputs/herdnet_baseline/20220413_HerdNet_General_dataset_2022.pth # Path to trained model checkpoint
  threshold: 0.5  # Detection confidence threshold (0.0-1.0)
  batch_size: 1  # Batch size for inference
  output_path: ./outputs/inference  # Output directory for inference results
  output_file: herdnet_baseline.csv  # Output file name for predictions
  detections_csv: herdnet_baseline_detections.csv  # Output filename for detections
  results_csv: herdnet_baseline_scores.csv  # Output filename for metrics/results

# Seed for reproducibility
seed: 9292
