# Configuration for calculating F1 scores on HerdNet predictions

# Ground truth annotations
gt_csv_path: data/herdnet/raw/groundtruth/csv/test_big_size_A_B_E_K_WH_WB.csv

# Predictions from model
pred_csv_path: outputs/inference/herdnet_baseline_detections.csv

# Output path for F1 score results
output_csv_path: outputs/metrics/herdnet_f1_scores.csv

# Prediction format: 'rfdetr', 'herdnet', or 'auto' to auto-detect
prediction_format: herdnet

# Distance threshold in pixels for true positive match
# Detection center must be within this distance from GT center
distance_threshold: 20.0