dataset_type: herdnet
csv_path: data/herdnet/processed/delplanque/train.csv
images_dir: data/herdnet/processed/delplanque/train
name: herdnet_delplanque_train
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
