# Final prediction visualization configuration for HerdNet stage 2 model over test set
dataset_type: herdnet
csv_path: outputs/herdnet_baseline/stage_2.csv
gt_csv_path: data/herdnet/raw/groundtruth/csv/test_big_size_A_B_E_K_WH_WB.csv
images_dir: data/herdnet/raw/test
name: herdnet_inference_stage1
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
