dataset_type: herdnet
csv_path: outputs/inference/rfdetr_background_included_0_30.csv
gt_csv_path: data/herdnet/raw/groundtruth/csv/val_big_size_A_B_E_K_WH_WB.csv
images_dir: data/herdnet/raw/val
name: rfdetr_inference_val_included_background
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
