dataset_type: herdnet
csv_path: outputs/inference/rfdetr_detections_large_train_90.csv
gt_csv_path: data/herdnet/raw/groundtruth/csv/train_big_size_A_B_E_K_WH_WB.csv
images_dir: data/herdnet/raw/train
name: rfdetr_inference_large_train
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
