dataset_type: herdnet
csv_path: data/herdnet/processed/512/train/gt.csv
images_dir: data/herdnet/processed/512/train
name: herdnet_512_train
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
