# HerdNet train dataset visualization config
dataset_type: herdnet
csv_path: data/herdnet/test_patches/gt.csv
images_dir: data/herdnet/test_patches
name: herdnet_test
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
