# HerdNet train dataset visualization config
dataset_type: herdnet
csv_path: data/herdnet/val_patches/gt.csv
images_dir: data/herdnet/val_patches
name: herdnet_val
persistent: false
point_radius: 10
database_uri: mongodb://localhost:27017
