# HerdNet-specific patcher configuration
# Use this to prepare HerdNet training patches

# @package _global_

defaults:
  - default

# HerdNet patch configuration
patch_size: 512
overlap: 160  # Recommended overlap for stitching

# Paths for HerdNet dataset
images_root: ${oc.env:DATA_DIR,./data}/herdnet/train
dest_dir: ${oc.env:DATA_DIR,./data}/herdnet/train_patches
csv_path: ${oc.env:DATA_DIR,./data}/herdnet/train.csv

# Annotation handling
min_visibility: 0.1
min_area_ratio: 0.5  # Keep only bboxes with at least 50% of original area visible
save_all: false  # Only save patches with annotations
