# Ungulate test set patcher configuration
# Use this to prepare Ungulate dataset test patches

# @package _global_

defaults:
  - default

# Ungulate patch configuration
patch_size: 560
overlap: 160  # Recommended overlap for stitching

# Paths for Ungulate dataset
images_root: ${oc.env:DATA_DIR,./data}/ungulate
dest_dir: ${oc.env:DATA_DIR,./data}/ungulate/test_patches
csv_path: ${oc.env:DATA_DIR,./data}/ungulate/annotations-clean-name-pruned/test.csv

# Annotation handling
min_visibility: 0.3  # Higher threshold for bbox annotations
min_area_ratio: 0.5  # Keep only bboxes with at least 50% of original area visible
save_all: false  # Only save patches with annotations
