# Ungulate training set patcher configuration
# Use this to prepare Ungulate dataset training patches

# @package _global_

defaults:
  - default

# Ungulate patch configuration
patch_size: 560
overlap: 160  # Recommended overlap for stitching

# Paths for Ungulate dataset
images_root: ${oc.env:DATA_DIR,./data}/ungulate
dest_dir: ${oc.env:DATA_DIR,./data}/ungulate/train_patches
csv_path: ${oc.env:DATA_DIR,./data}/ungulate/annotations-clean-name-pruned/train.csv

# Annotation handling
save_all: false  # Only save patches with annotations
