# Ungulate validation set patcher configuration
# Use this to prepare Ungulate dataset validation patches

# @package _global_

defaults:
  - default

# Ungulate patch configuration
patch_size: 560
overlap: 160  # Recommended overlap for stitching

# Paths for Ungulate dataset
images_root: ${oc.env:DATA_DIR,./data}/ungulate
dest_dir: ${oc.env:DATA_DIR,./data}/ungulate/val_patches
csv_path: ${oc.env:DATA_DIR,./data}/ungulate/annotations-clean-name-pruned/val.csv

# Annotation handling
save_all: false  # Only save patches with annotations
